print("Moon" in "Space travel is important as it helps discover space.")
print("Moon" in "This text will describe Moon as Moon is important")
temperature = """Saturn has a daytime temperature of -170 degrees Celsius, while Mars has -28 Celsius."""
print(temperature.find("Moon"))
print(temperature.find("Mars"))
print(temperature.count("Moon"))
print(temperature.count("Mars"))
print(temperature.count("Celsius"))
print("THE MOON AND THE EARTH".lower())
print("the moon and the earth".upper())